version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: db_rnip_server
    restart: unless-stopped
    environment:
      POSTGRES_DB: rnip_db
      POSTGRES_USER: rnip_user
      POSTGRES_PASSWORD: rnip_password
    ports:
      - "6432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
