spring:
  application:
    name: rnip-server
  datasource:
    url: jdbc:postgresql://localhost:6432/rnip_db
    password: rnip_password
    username: rnip_user
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

#  main:
#    allow-bean-definition-overriding: true
logging:
  level:
    root: info
    org.springframework:
      oxm.jaxb.Jaxb2Marshaller: trace
      ws: trace